# yaml-language-server: $schema=https://raw.githubusercontent.com/fern-api/fern/main/fern.schema.json

imports:
  commons: commons.yml

services:
  http:
    ModelConfigurationService:
      auth: true
      base-path: /projects/{project_id}/model-configs
      path-parameters:
        project_id: string
      endpoints:
        getProjectModelConfigsProjectsProjectIdModelConfigsGet:
          path: ""
          method: GET
          docs: Get an array of model_configs associated to your project
          display-name: Get Project Model Configs
          response: >-
            list<commons.ProjectModelConfigResponse>

        deleteProjectModelConfigProjectsProjectIdModelConfigsModelConfigIdDelete:
          path: /{model_config_id}
          method: DELETE
          docs: Delete a model configuration from your project.
          display-name: Delete Project Model Config
          path-parameters:
            model_config_id: string

        updateProjectModelConfigProjectsProjectIdModelConfigsModelConfigIdPatch:
          path: /{model_config_id}
          method: PATCH
          docs: Update a model configuration within your project
          display-name: Update Project Model Config
          path-parameters:
            model_config_id: string
          request:
            body: UpdateProjectModelConfigRequest
          response: >-
            commons.ProjectModelConfigResponse

types:
  UpdateProjectModelConfigRequest:
    properties:
      display_name: optional<string>
      description: optional<string>
